server:
  port: 8989

eureka:
  client:
    serviceUrl:
      defaultZone: http://54.70.136.53:8761/eureka/    
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    
turbine:
  aggregator:
    clusterConfig: ORDER
  appConfig: order

  
